if matlabpool('size') == 0
	matlabpool('open');
end

clear;
close all;
load('InitialX.mat');
solvers = {'derand1bin'};
measureOptions.Dimension = 30;
measureOptions.Runs = 51;
measureOptions.MaxFunEvals = measureOptions.Dimension * 1e4;
measureOptions.LowerBounds = -100;
measureOptions.UpperBounds = 100;
measureOptions.FitnessFunctions = {...
	'cec13_f1', 'cec13_f2', 'cec13_f3', 'cec13_f4', ...
	'cec13_f5', 'cec13_f6', 'cec13_f7', 'cec13_f8', 'cec13_f9', ...
	'cec13_f10', 'cec13_f11', 'cec13_f12', 'cec13_f13', ...
	'cec13_f14', 'cec13_f15', 'cec13_f16', 'cec13_f17', ...
	'cec13_f18', 'cec13_f19', 'cec13_f20', 'cec13_f21', ...
	'cec13_f22', 'cec13_f23', 'cec13_f24', 'cec13_f25', ...
	'cec13_f26', 'cec13_f27', 'cec13_f28'};
solverOptions.dimensionFactor = 5;
solverOptions.NP = solverOptions.dimensionFactor * measureOptions.Dimension;
solverOptions.F = 0.7;
solverOptions.CR = 0.5;
solverOptions.Q = 70;
solverOptions.RecordPoint = 21;
solverOptions.ftarget = 1e-8;
solverOptions.TolX = 0;
solverOptions.TolStagnationIteration = Inf;
solverOptions.initial.X = eval(sprintf('XD%dNP%d', ...
	measureOptions.Dimension, ...
	solverOptions.NP));

for isolver = 1 : numel(solvers)
	startTime = tic;
	date = datestr(now, 'yyyymmddHHMM');	
	solver = solvers{isolver};
	[allout, allfvals, allfes, T0, T1, T2] = complete_cec13(...
		solver, ...
		measureOptions, ...
		solverOptions);
		
	elapsedTime = toc(startTime);
	if elapsedTime < 60
		fprintf('Elapsed time is %f seconds\n', elapsedTime);
	elseif elapsedTime < 60*60
		fprintf('Elapsed time is %f minutes\n', elapsedTime/60);
	elseif elapsedTime < 60*60*24
		fprintf('Elapsed time is %f hours\n', elapsedTime/60/60);
	else
		fprintf('Elapsed time is %f days\n', elapsedTime/60/60/24);
	end
	
	save(sprintf('complete_cec13_%s.mat', date), ...
		'allout', ...
		'allfvals', ...
		'allfes', ...
		'T0', 'T1', 'T2', ...
		'solver', ...
		'measureOptions', ...
		'solverOptions', ...
		'elapsedTime');
end