function run_errors_cons_minmax_all
startTime = tic;
solvers = {...
	'mmdeb1b_o', ...
	'mmdeb1b_p', ...
	'mmdeb1b_c', ...
	'mmdeb1b_e', ...
	'mmdeb1b_pc', ...
	'mmdeb1b_pe', ...
	'mmdeb1b_ce', ...
	'mmdeb1b_pce', ...
	'mmder1b_o', ...
	'mmder1b_pce', ...
	'mmjade_o', ...
	'mmjade_pce', ...
	'mmsade_o', ...
	'mmsade_pce', ...
	'mmshade_o', ...
	'mmshade_pce'};

funcalls = {...
	'run_errors_cons_minmax1', ...
	'run_errors_cons_minmax2'};

for i = 1 : numel(funcalls)
	for j = 1 : numel(solvers)
		feval(funcalls{i}, solvers{j});
	end
end

toc(startTime);
end
