filenames={'CEC14_D50_Q21_CONV','CEC14_D50_Q21_QDYN','CEC14_D50_Q21_XSTD'};
titlenames={'CEC14 D50 Q21 CONV','CEC14 D50 Q21 QDYN','CEC14 D50 Q21 XSTD'};
methodnames={'dcmaeabin','dcmaea_s','deglbin','degl_s','jadebin','jade_s','rbdebin','rbde_s','sadebin','sade_s','shade','shade_s'};
clr=[...
    0 0 0;...
    1 0 0;...
    0 1 0;...
    0 0 1;...
    1 1 0;...
    0 1 1;...
    1 0 1;...
    1 0.5 0;...
    1 0 0.5;...
    0.5 1 0;...
    0 0.5 1;...
    0.5 1 0.5];
for i=1:length(filenames)
%     filenames{i}=filenames{i}(1:find(filenames{i}=='.')-1);
    filenames{i}=[filenames{i},'.xlsx'];
end
ptfnm='.png';
for i=1:length(filenames)
    for k=2:31
        fg=figure('visible','off');
        for j=12:23
            xls=xlsread(filenames{i},j);
            semilogy(xls(1,:),xls(k,:),'color',[clr(j-11,1) clr(j-11,2) clr(j-11,3)]);
            hold on
        end
        legend(methodnames,1);
        %         axis([1,2000,0,1])
        ylabel('err.');
        xlabel('gen.');
        title([titlenames{i},' f',num2str(k-1)]);
        saveas(fg,[filenames{i},'_f',num2str(k-1),ptfnm]);
        hold off
    end
end